### ISSUE TITLE
iOS Subscription Offers for Flutter

### ISSUE THREAD

**Issue by CarlosMedina10** [RevenueCat/purchases-flutter#109]
I see its supported for Swift , objective-C and React native
https://docs.revenuecat.com/docs/ios-subscription-offers

Is there any way to implement subscription with free trial in flutter?

**Comment by aboedo** [comment]
support for subscription offers has actually just been merged! https://github.com/RevenueCat/purchases-flutter/pull/104

It'll be a part of the 1.4.0 release, coming soon. We'll also update the docs to include flutter examples when this gets released. 

I'm closing this ticket since it's a duplicate of https://github.com/RevenueCat/purchases-flutter/issues/25, and that one was closed when the subscription offers PR was merged.

**Comment by CarlosMedina10** [comment]
Hello, I see in your recent release its implemented iOS subscription offers for flutter.


Can you give an example of how to use please?

Thanks you very much!
