### ISSUE TITLE
How to manual trigger renewal even if my subscription is active?

### ISSUE THREAD

**Issue by repsajanboy** [RevenueCat/purchases-flutter#119]
Hi guys I've been using revenuecat to set up an in-app purchase for our app, our product is set to subscription and currently it auto renew if the period is over, What I want is to renew again even if the subcription for the previous purchase is active. Is that possible? Thanks.

**Comment by rkotzy** [comment]
Hi 👋 ! Going to close this out since it doesn't appear to be a specific issue with the Flutter SDK. 

You can read more about testing subscriptions here: https://docs.revenuecat.com/docs/sandbox

Apple/Google have there own set of restrictions around what can be done in sandbox environments and it sounds like you may be bumping up against those.
