### ISSUE TITLE
It always show 220/10 min but it's 1 month plan..

### ISSUE THREAD

**Issue by chirag-chopra** [RevenueCat/purchases-flutter#124]
![cccc](https://user-images.githubusercontent.com/22336412/97472756-328c0200-1970-11eb-921f-bcd7ab5c5fb4.jpeg)

I am using latest version of flutter which is 1.22.2 stable

Why it is showing so?

**Comment by vegaro** [comment]
Hi! This is only shown for license testers in the "sandbox" environment. Test purchases have a shorter renewal rate so that it's easier to test them.

You can find more information about it here: https://developer.android.com/google/play/billing/test#renewals

And:

https://docs.revenuecat.com/docs/google-play-store#working-with-subscriptions

The only way you have to test the real duration is releasing the app to a test track and purchasing the subscription with a non license tester. I recommend reading this article from Google https://developer.android.com/google/play/billing/test since it explains a lot of these concepts. 

I hope that helps.
