### ISSUE TITLE
Can't build the app

### ISSUE THREAD

**Issue by IliaKhuzhakhmetovRoonyx** [RevenueCat/purchases-flutter#129]
`Module 'Purchases' not found`

Library version is - 1.4.5
xCode version is - 12.1

**Comment by aboedo** [comment]
hi! thanks for reporting. 
please try: 
- deleting derived data in xcode https://programmingwithswift.com/delete-derived-data-xcode/
- in the `ios` folder in your project, run `pod clean`
- then `flutter build ios`.

**Comment by aboedo** [comment]
@IliaKhuzhakhmetovRoonyx did you manage to figure this out?

**Comment by IliaKhuzhakhmetovRoonyx** [comment]
@aboedo Yes, i did.

For success build i did this:
In `PurchasesFlutterPlugin.h` i changed `@import Purchases` to `#import <Purchases/Purchases.h>`

**PurchasesFlutterPlugin.h**
```
#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif
#import <Purchases/Purchases.h>

@interface PurchasesFlutterPlugin : NSObject<FlutterPlugin>
@end
```

**Comment by aboedo** [comment]
@IliaKhuzhakhmetovRoonyx that's interesting 🤔 . The `@import` syntax should work as long as modules are enabled for the project (the `ENABLE_MODULES` setting in build settings), and that's supposed to automatically be set by Cocoapods, since it's set in the `podspec` file. But flutter or the app may be overriding the value either in the project settings or xcconfig files. 

Closing this for now. 
Thanks for the update!

**Comment by TobiasPalludan** [comment]
@aboedo in [this](https://github.com/RevenueCat/purchases-flutter/issues/142#issuecomment-762260129) you mention this issue and to `pod clean`. I think `pod clean` was replaced by `pod cache clean --all`?
#142 and, in turn, this issue shows up when searching for that error.

**Comment by aboedo** [comment]
@TobiasPalludan that's correct, the syntax now would be `pod cache clean --all`. Are you running into this issue? If so, would you mind opening a new ticket so we can figure it out? 

That way, folks who were subscribed to this thread don't get notifications while we figure out what's going on with your case.
