### ISSUE TITLE
All the date related properties should be DateTime type

### ISSUE THREAD

**Issue by jezsung** [RevenueCat/purchases-flutter#137]
Currently, RevenuCat Flutter SDK returns String for the date related properties but it would be better if it's typed to DateTime.

And how do I convert String to DateTime? The string is formatted like `'2020-12-15T05:17:11Z'`. How do I get a local time so that I can show the correct formatted date.

**Comment by rkotzy** [comment]
Please use https://support.revenuecat.com/hc/en-us/articles/360046422033-Feature-Requests instead of opening an issue. That is the best channel that allows product teams to keep track of feature requests.

The date strings are in ISO 8601 format. It looks like DateTime should be able to parse those automatically: https://api.flutter.dev/flutter/dart-core/DateTime/parse.html
