### ISSUE TITLE
Improve Errors

### ISSUE THREAD

**Issue by smkhalsa** [RevenueCat/purchases-flutter#141]
I'd like to be able to automatically restore a product if I receive an "ITEM_ALREADY_OWNED" error when purchasing a product.

However, the existing exception is nested deep inside a `PlatformException`, and it's difficult to parse.

**Comment by rkotzy** [comment]
Hey @smkhalsa 👋 . The "ITEM_ALREADY_OWNED" is an Android specific error which is why it's nestled under the `PlatformException` in the Flutter SDK. We do have a feature request on the backlog for something similar that should work cross-platform, but would be a call to check if the product is already owned before the makePurchase call.

**Comment by smkhalsa** [comment]
@rkotzy that's great. Is there another issue ok GitHub for the feature? How can I track progress?
