### ISSUE TITLE
getProducts(), type 'List<dynamic>' is not a subtype of type 'FutureOr<List<Product>>'

### ISSUE THREAD

**Issue by marchacio** [RevenueCat/purchases-flutter#163]
Hi everyone.
In my app, i have added the method "Purchases.getProducts(...)" but this throws a TypeError Exception.
VScode shows me that the corrupted file is "purchases_flutter.dart".

Today I upgraded the package to 3.0.0; before today, i used 2.0.2 

**My code:**
```
Future<List<Product>> caricaDonazioni() async {
    List<Product> prodotti = await Purchases.getProducts([
      'XXXXX',
      'XXXXX',
      'XXXXX',
      'XXXXX',
      'XXXXX',
    ], type: PurchaseType.inapp);

    prodotti.sort((prod1, prod2) => prod1.price.compareTo(prod2.price));

    return prodotti;
  }
```

**Comment by vegaro** [comment]
Can you share the exception? I would like to look at the stacktrace. Thanks!

**Comment by davidmartos96** [comment]
@vegaro I think that the problem is that the typing of invokeMethod has been removed, so that turns into dynamic.

Dynamic doesn't statically check the .map, but fails to infer the output type as List<Product>.

Probably bring the List<dynamic> back would fix it. Maybe it could help to deactivate the implicit dynamic lint to better spot/avoid these kind lf issues. 
dynamic is too magical 😄

**Comment by vegaro** [comment]
As you say, bringing back `List<dynamic>` as the type fixes it, but also adding `map<Product>` and keeping the `final result`. What you are saying makes sense. For future reference, what's basically happening is:

1. Replacing `List<dynamic>` with `final` is making the result to be of type `dynamic`.
1. The static analyzer doesn't check the type of `map` because result is `dynamic`. We can specifically tell that `map` should be `map<Product>`, or just make sure that `result` is not `dynamic`

I was actually just looking at how to disable the `implicit-dynamic` lint because these issues look insanely hard to spot unless you have a ton of experience with the language, which I don't.

**Comment by vegaro** [comment]
I am preparing a release 3.0.1 that should include the fix. Thanks for reporting and sorry about the trouble

**Comment by nohli** [comment]
> As you say, bringing back `List<dynamic>` as the type fixes it, but also adding `map<Product>` and keeping the `final result`. What you are saying makes sense. For future reference, what's basically happening is:
> 
> 1. Replacing `List<dynamic>` with `final` is making the result to be of type `dynamic`.
> 2. The static analyzer doesn't check the type of `map` because result is `dynamic`. We can specifically tell that `map` should be `map<Product>`, or just make sure that `result` is not `dynamic`
> 
> I was actually just looking at how to disable the `implicit-dynamic` lint because these issues look insanely hard to spot unless you have a ton of experience with the language, which I don't.

@vegaro this is how to disable that lint:

```
analyzer:
  strong-mode:
    implicit-dynamic: false
```
Would you like a PR?

**Comment by vegaro** [comment]
Thanks @nohli ! I actually have a branch and have started fixing a bunch of errors.  There are so many though :facepalm:
