### ISSUE TITLE
purchaserInfo.entitlements.all.size = 0 when first launch of the app

### ISSUE THREAD

**Issue by dpedrinha** [RevenueCat/purchases-flutter#172]
Hi.

Here's the scenario (sandbox).

I install the app, run it and make a recurrent monthly subscription. It goes active, I get charged on my fake credit card and everything is fine. 

But, if I uninstall the app and install it again, the first time the app runs I get `purchaserInfo.entitlements.all.size = 0 and purchaserInfo.entitlements.active.size = 0`. In other words, I get no entitlements.

I should get my entitlements and there should be one active, since uninstalling apps doesn't cancel subscriptions.

If I force close the app and run it again, this second time, it works as it should: I get my entitlements and the active subscription.

But why am I not getting it on the first run after uninstall and install?

Here's my code run when the app starts:

```
Future<void> initPlatformState() async {
    await Purchases.setDebugLogsEnabled(true); //TODO REMOVE FOR DEPLOY
    await Purchases.setup("my_key"); 

    try {
      purchaserInfo = await Purchases.getPurchaserInfo();
      
      if (purchaserInfo.entitlements.all['vip'] != null) {
        setIsPro(purchaserInfo.entitlements.all['vip'].isActive);
      } else {
        setIsPro(false);
      }
    } on PlatformException catch (e) {
      print('\n###########################\nPlatformException: ' + e.toString() + '\n###########################\n');
    }
    print('\n###########################\n is user pro? ' + isPro.toString() + '\n###########################\n');
  }
```

In this code, the `else `is called every first run of the app (after uninstall and install) because `purchaserInfo.entitlements.all['vip']` returns `null`.

But as soon as I close and open the app again, I get the object and `purchaserInfo.entitlements.all['vip'].isActive` equals `true` until the subscription expires or I cancel it.

I'm testing it on Android, I haven't tested iOS yet because of plugins, dart, pods and ios usual incompatibility after every update. I don't have time to deal with it now.

**Comment by rkotzy** [comment]
This sounds like expected behavior. RevenueCat links subscription status to an app user Id, not a device. So when you uninstall / reinstall all of the caches are cleared, the user Id is reset, so the subscription status is expected to be "inactive". 

In the background, things are getting synced up with the new app user Id so on the next launch you see their subscribed. If you set up the purchaserInfoUpdated listener you should see this as it happens. 

If you're able to look at the debug logs that reproduce this you can confirm if this is the case: https://docs.revenuecat.com/docs/debugging

**Comment by dpedrinha** [comment]
> This sounds like expected behavior. RevenueCat links subscription status to an app user Id, not a device. So when you uninstall / reinstall all of the caches are cleared, the user Id is reset, so the subscription status is expected to be "inactive".
> 
> In the background, things are getting synced up with the new app user Id so on the next launch you see their subscribed. If you set up the purchaserInfoUpdated listener you should see this as it happens.
> 
> If you're able to look at the debug logs that reproduce this you can confirm if this is the case: https://docs.revenuecat.com/docs/debugging

It makes sense, but it doesn't explain why `purchaserInfo.entitlements.all.size == 0`.

If `isActive` came false for all entitlements, your explanation would make sense. But even then, since it's an asynchronous process, it would be much better if `Purchases.setup()` didn't return until it gets the `userID`. I don't know if it's possible, since it envolves background Android syncing, but, it's a suggestion.

I can confirm that the listener does the trick though. The code bellow works every time:

```
Future<void> initPlatformState() async {
    await Purchases.setDebugLogsEnabled(true); //TODO REMOVE FOR DEPLOY
    await Purchases.setup("akjsdhflkadjshflkadsjhflakdsjl");

    try {
      purchaserInfo = await Purchases.getPurchaserInfo();
      _checkIfVIP(purchaserInfo);
    } on PlatformException catch (e) {
      print('\n###########################\nPlatformException: ' + e.toString() + '\n###########################\n');
    }
    
    Purchases.addPurchaserInfoUpdateListener((info) {
      _checkIfVIP(info);
    });

  }

  void _checkIfVIP(PurchaserInfo purchaserInfo) {
    if (purchaserInfo.entitlements.all['vip'] != null) {
      setIsPro(purchaserInfo.entitlements.all['vip'].isActive);
    } else {
      setIsPro(false);
    }
  }
```

But now _checkIfVip() always run twice and I don't know if I can rely on the listener only.

Would it be a good practice to do something like that?

```
Future<void> initPlatformState() async {
    await Purchases.setDebugLogsEnabled(true); //TODO REMOVE FOR DEPLOY
    Purchases.addPurchaserInfoUpdateListener((info) {
      _checkIfVIP(info);
    });
    await Purchases.setup("oZXTYSRdtjShZYSUnnkUigPzHUOlplKv");
  }
```

I'm concerned because the docs says the listener is optional so it probably wasn't meant to be used this way.

But honestly, this is another suggestion that would make it much better.

I'll test it for a while but in principle this last one is the best, cleanest and optimal approach (if it works) to run when the app starts.

**Comment by rkotzy** [comment]
>It makes sense, but it doesn't explain why purchaserInfo.entitlements.all.size == 0

The entitlements array will only contain entitlements that the customer has purchased - not every entitlement configured in the dashboard. Sorry for any confusion here! In this case since it's a new App User Id after reinstalling, they don't have any entitlements yet.

>But now _checkIfVip() always run twice and I don't know if I can rely on the listener only. Would it be a good practice to do something like that?

I would test and confirm it's okay for your code to be executed multiple times, but you should be all good to rely on the listener here.

>IMHO, If the behavior I'm reporting here is expected, then the docs should be updated to put the listener as mandatory in the app start code.

Restores are the recommended way to re-sync the device subscription status with the current App User Id: https://docs.revenuecat.com/docs/getting-started#restoring-purchases. Developers shouldn't lose any functionality by not implementing the listener - in these cases the customer would usually tap a "restore purchases" button. 

It's probably worth noting here that the background syncing that is occurring on Android does not happen the same way on iOS. If the app is uninstalled / reinstalled and you aren't setting your own App User Id between installations, the typical behavior is to have customers restore purchases.

Hope all this helps! Going to close out this issue since it doesn't seem to be a bug with the Flutter SDK, but will pass this on to our Dev Support Engineers to see if there's some updates to the documentation we could make.
