### ISSUE TITLE
$displayName Attribute Deprecated?

### ISSUE THREAD

**Issue by emadd** [RevenueCat/purchases-flutter#190]
Getting an error when setting attribute $displayName.  Documentation does not corroborate this claim.

[Purchases] - ERROR: 😿‼️ Error when syncing subscriber attributes. Details: One or more of the attributes sent could not be saved.
 UserInfo:{
    NSLocalizedDescription = "One or more of the attributes sent could not be saved.";
    NSUnderlyingError = "Error Domain=RCBackendErrorDomain Code=7263 \"Some subscriber attributes keys were unable to be saved.\" UserInfo={NSLocalizedDescription=Some subscriber attributes keys were unable to be saved.}";
    "attribute_errors" =     (
                {
            "key_name" = "$displayName";
            message = "A newer value exists for this attribute.";
        }
    );
    "readable_error_code" = "INVALID_SUBSCRIBER_ATTRIBUTES";
    successfullySynced = 1;
}

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2019.2)
[✓] VS Code (version 1.55.2)
[✓] Connected device (3 available)

**Comment by vegaro** [comment]
Hi @emadd thanks for opening this issue. `$displayName` hasn't been deprecated. The error you're getting means that the backend has already saved `$displayName` with another value, and that attribute has a more recent timestamp than the one you are sending. The SDK won't try to sync this value again, since the backend would return the same error. 

Is it possible you synced the attribute before? Maybe with a different device?
