### ISSUE TITLE
App rejected by apple, completing purchase

### ISSUE THREAD

**Issue by armandojimenez** [RevenueCat/purchases-flutter#204]
- [ x] I have updated Purchases SDK to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/develop/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [ x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
My app keeps getting rejected by apple with this:
Guideline 2.1 - Performance - App Completeness

We found that your in-app purchase products exhibited one or more bugs when reviewed on iPad running iOS 14.6 on Wi-Fi.

The displayed an error message when we tried to purchase a premium product.

Please see attached screenshot for details.

Steps to reproduce: 

- Navigate to the subscription page
- Select an option
- Tap "Continue"
- Add our Apple ID password and proceed with 
- The purchase interface loaded for several minutes
- the error message appreared

It works fine on TestFlight and Sandbox, so I'm not able to replicate the issue, what can I do? docs in help center are not helpful since I dont know the error and crashlytics is not reporting errors. I really need help

1. Environment
   1. Output of `flutter doctor`
   2. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**
Using latest package on dev channel

**Comment by vegaro** [comment]
Unfortunately, Apple's sandbox environment is notoriously flaky - there are regular outages and sometimes purchases can get hung up in their system. Most of the time this error is due to sandbox downtime, but you can read about all the causes for this error in our guide on error handling here: https://docs.revenuecat.com/docs/errors#--store_problem

Even worse is that Apple's reviewers use this unstable environment for App Review, which can cause issues when the reviewer tests in-app purchases like subscriptions. I would recommend re-submitting your app for review (some developers have submitted the same binary up to a dozen times before getting through).

Just to clarify, there's nothing you as a developer or RevenueCat can do to resolve these errors except retrying later/resubmitting.

The good news is that Apple uses a separate production environment that is much more stable for live purchases, and these issues aren't often seen in the same manner as in the sandbox environment. Additionally, this typically only happens when an app is being launched for the first time- subsequent updates typically work as expected for the reviewer.

**Comment by armandojimenez** [comment]
So do you recommend that I create a new build, re-submit the same build? or try to appeal the reject and tell them to try again?

**Comment by vegaro** [comment]
You can try to appeal, but that pretty much never works. You could ask them to review the products first and then review the app, but you need to submit a new build regardless since they rejected the binary.

We hope they figure a way to prevent this sort of errors because we get a lot of instances of them and we can't really do anything about it...

Hopefully they accept your app soon.

**Comment by armandojimenez** [comment]
Ok thanks! I will keep trying

**Comment by armandojimenez** [comment]
Also, their attempts to purchase are not showing on RevenueCat sandbox data, this is normal right?

**Comment by armandojimenez** [comment]
And both my binary and IAP are in waiting for review status, the first time I submitted the binary, I attached the IAP, is that good or the IAP needs to be in Approved first?

**Comment by vegaro** [comment]
Yeah, products should be approved first. Apple should review your products first, but sometimes they just don't do it for some reason... You can recommend them to do that and see if that helps.

**Comment by armandojimenez** [comment]
Got just approved, I did another build without changing anything, and it passed, this can be closed now. Thanks for the help!
