### ISSUE TITLE
[QUESTION] getOfferings vs getProducts 

### ISSUE THREAD

**Issue by Jayvd** [RevenueCat/purchases-flutter#205]
Hi, I am sorry if this is not the right place to ask this, but, after looking at the examples, I am wondering:

**1**. Why do they all Display the IAP using the `Purchases.getOfferings`, instead of `Purchases.getProducts` ?

**2**. Is it possible to `getProducts` that has a regular IAP and subscription IAP together? Because it seems to take an additional `PurchaseType` parameter. 

`List<Product> products = await Purchases.getProducts(["Monthly_Subscription","OneTimePayment"], type: PurchaseType.subs );`

**3**. Once we successfully retrieve the Products using `getProducts`. How do we make a purchase using that retrieved product? 

Thank you and sorry again

**Comment by aboedo** [comment]
Oh gosh, I'm not sure how this question slipped our radar, but I apologize. 

The best place to ask this kind of question is [in our community](https://community.revenuecat.com/). 
We reserve GitHub issues for bug reports only. 

As for those particular questions: 

We have methods for `getOfferings` and `getProducts`. `Offerings` provide a layer of abstraction on top of products, which makes them easier to work in, particularly in Flutter - an offering will abstract away the underlying `Product` object, which will be different for Android and iOS. 
In addition, `Offerings` offer a few conveniences to make it easier to set up a paywall, like grouping products into packages with associated durations and allowing you to show different groupings of products depending on the situation. 

There's more information on how Offerings work and their differences with Products [here](https://docs.revenuecat.com/docs/entitlements). 

I'd recommend in general sticking to Offerings, since they offer more flexibility and are easier to use in a multi-platform environment. 

And yes, `getProducts` will actually fetch any products that are set up with the identifiers that are passed in, regardless of whether they're subscriptions, consumables, etc. 

There's detailed information for how to make a purchase [here.](https://docs.revenuecat.com/docs/making-purchases)

If you follow the documentation in order, it should lead you through the flow of getting the user's purchasing info, displaying products, making purchases and granting entitlements. 

Again, if you need more information, the best places are: 

- [Our docs](https://docs.revenuecat.com/docs/) for tutorials and general explanations. 
- [Our community](https://community.revenuecat.com/) for questions and tips.
- [Our support](https://support.revenuecat.com/) if you need help with something specific that doesn't seem to be working. 
- [GitHub issues] to report bugs in the SDK.

Hope this helps! 

I'm closing out this issue for now since we reserve GitHub issues for bug reports only.
