### ISSUE TITLE
Package support

### ISSUE THREAD

**Issue by kofan** [RevenueCat/purchases-flutter#21]
Is the package going to be actively supported and evolving? I see that SDK for android and iOS get regularly updated, although there are no commits to flutter SDK for more than a month...

**Comment by aboedo** [comment]
@kofan sorry for the delayed response. purchases-flutter is still actively maintained and evolving. 
The android and iOS SDKs get commits more often because they're the base SDKs, the other SDKs use their code underneath. purchases-flutter and other SDK versions integrate changes from iOS and android as soon as they're ready.

**Comment by kofan** [comment]
Ok, I see! Thanks for the response!
