### ISSUE TITLE
Error on iPad and iPhone running iOS 14.6 on Wi-Fi

### ISSUE THREAD

**Issue by Jayvd** [RevenueCat/purchases-flutter#211]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/develop/CONTRIBUTING.md)
- [V] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [V] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [V] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

We found that your in-app purchase products exhibited an error when reviewed on iPhone and iPad running iOS 14.6 on Wi-Fi.

When validating receipts on your server, your server needs to be able to handle a production-signed app getting its receipts from Apple’s test environment. The recommended approach is for your production server to always validate receipts against the production App Store first. If validation fails with the error code "Sandbox receipt used in production," you should validate against the test environment instead.
I buy a 1-month subscription for my application and it is implemented successfully. But when I want to buy it again after the test period, I encounter a problem, it says the purchase is unsuccessful and the purchase window does not appear, but when I buy a 6-month and annual package, the purchase windows come.

**Comment by rkotzy** [comment]
Hi 👋! This appears to be a generic rejection reason from the App Store Review team.

We've put together a guide on handling App Store rejections that can hopefully help: https://docs.revenuecat.com/docs/app-store-rejections

Going to close this out since it doesn't appear to be a bug related to the Purchases Flutter SDK or RevenueCat's handling of sandbox vs production receipt validation.
