### ISSUE TITLE
Recompile with -Xlint:deprecation for details. Warning

### ISSUE THREAD

**Issue by Jayvd** [RevenueCat/purchases-flutter#213]
- [ ] I have updated Purchases SDK to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/develop/CONTRIBUTING.md)
- [ ] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [ ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

I get this message when compiling, any ideas why?

Thank you

```
Note: /Users/jayvd/.pub-cache/hosted/pub.dartlang.org/purchases_flutter-3.3.1/android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by aboedo** [comment]
Hi @Jayvd 👋 Thanks for reporting! 

You're correct! There are a few deprecated things we're using. 
We'll update those.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/3922667/124312929-87f36100-db46-11eb-9763-203f19c2cf28.png">

Thanks again!

**Comment by daveshirman** [comment]
Is there any rough timeline on when this will be amended please?

The fewer deprecated APIs that are accessed, the less the chance of the app not building in the near future. 

Thanks.

**Comment by aboedo** [comment]
@daveshirman I don't have an exact ETA, however, for this particular case, removing the deprecated API usage isn't really an option:

The deprecations that get referenced by the warning are all related to flutter's v1 plugin format. Since 1.12, Flutter's had a new format for plugins to use, which introduces better handling of the app's lifecycle. 

We [upgraded to the new format back in June 2020](https://github.com/RevenueCat/purchases-flutter/commit/da374dae3c19a843c21cb77c5296d1c48e969655), however, Flutter recommends that we [keep the old methods around](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration#upgrade-steps) for apps that use the v1 method of embedding. 

So the best path to follow for this particular case is to suppress the deprecation warnings, and remove the methods once v1 support is removed, which might take a long time. 

This is also what Flutter itself is doing for their plugins, [see this example](https://github.com/flutter/plugins/blob/4383bb15d91384efb22dbe409c3fd58e4552267c/packages/battery/battery/android/src/main/java/io/flutter/plugins/battery/BatteryPlugin.java#L34). 

I'll open up a PR for the suppressed warnings in a bit. 

Rest assured, however, that if / when Flutter does remove support for the old APIs (perhaps in 3.0?), we'll make sure that our plugin still works and doesn't lead to developer headaches.

**Comment by aboedo** [comment]
Release 3.4.2 is out with the fix! Closing this now

**Comment by daveshirman** [comment]
@aboedo Strange, I updated this morning to 3.4.2 and when I build for android I get this still in my build log:

```
Note: /Users/daveshirman/Documents/Work/flutter/.pub-cache/hosted/pub.dartlang.org/purchases_flutter-3.4.2/android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java uses or overrides a deprecated API.
```

**Comment by aboedo** [comment]
@daveshirman you're correct, my apologies. 
I thought I'd caught them all, but the compiler still complains about references to the types in the imports. I'm re-opening and opening up a PR with the fix.

**Comment by aboedo** [comment]
release 3.4.3 is out with the new fix, @daveshirman let me know if you're still running into issues!

**Comment by daveshirman** [comment]
Looks good my end, thank you!

**Comment by aboedo** [comment]
@daveshirman thanks so much for reporting back! I'm glad things are looking good now 🎉 
Have a great day!

**Comment by slefter** [comment]
Hello, this issue reappeared.
I use version 4.12.0 of purchases_flutter package.
The message I get when compiling is:
`Note: C:\Users\user\AppData\Roaming\Pub\Cache\hosted\pub.dev\purchases_flutter-4.12.0\android\src\main\java\com\revenuecat\purchases_flutter\PurchasesFlutterPlugin.java uses or overrides a deprecated API.`
