### ISSUE TITLE
MobX store is not genertaed when revenucat refferenced.

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [RevenueCat/purchases-flutter#230]
Hello,

I noticed that my mobx store stoped generating when i refference package.
This example generates ```subscriptions_page.store.g.dart``` file
```
import 'package:mobx/mobx.dart';

part 'subscriptions_page.store.g.dart';

class SubscriptionsPageStore extends _SubscriptionsPageStore with _$SubscriptionsPageStore {}

abstract class _SubscriptionsPageStore with Store {
  var products = ObservableList<dynamic>();

  @observable
  bool isLoading = false;

  addData(List<dynamic>? value) {
    products.clear();
    products.addAll(value!);
    isLoading = false;
  }

  @action
  resetStore() {
    isLoading = false;
  }
}
```

This example dose not:
```
import 'package:mobx/mobx.dart';
import 'package:purchases_flutter/purchases_flutter.dart';

part 'subscriptions_page.store.g.dart';

class SubscriptionsPageStore extends _SubscriptionsPageStore with _$SubscriptionsPageStore {}

abstract class _SubscriptionsPageStore with Store {
  var products = ObservableList<Product>();

  @observable
  bool isLoading = false;

  addData(List<Product>? value) {
    products.clear();
    products.addAll(value!);
    isLoading = false;
  }

  @action
  resetStore() {
    isLoading = false;
  }
}
```

any thoughts?

**Comment by aboedo** [comment]
@vytautas-pranskunas- I'm actually not sure what would cause this, do you get any build logs or warnings that might indicate an issue on the mobx side?

**Comment by vytautas-pranskunas-** [comment]
Nop, just generated file does not appear.

**Comment by aboedo** [comment]
@vytautas-pranskunas- I tried this out and I can confirm that I run into the same thing you did. 
Generation completes successfully but doesn't actually generate the file if you import purchases. 

The reason is that both `purchases-flutter` and `mobx` define an object called `Store`, so you need to disambiguate by adding a prefix to one of the imports. 
After adding the prefix, every time you use a type from the package that you added an import to, you prefix it. 

In your example, this would become (I'm adding an import to mobx, but you could do it to purchases too): 

```dart
import 'package:mobx/mobx.dart' as mobx;
import 'package:purchases_flutter/purchases_flutter.dart';
part 'subscriptions_page.store.g.dart';

class SubscriptionsPageStore extends _SubscriptionsPageStore
    with _$SubscriptionsPageStore {}

abstract class _SubscriptionsPageStore with mobx.Store {
  var products = mobx.ObservableList<dynamic>();

  @mobx.observable
  bool isLoading = false;

  addData(List<dynamic>? value) {
    products.clear();
    products.addAll(value!);
    isLoading = false;
  }

  @mobx.action
  resetStore() {
    isLoading = false;
  }
}
```

Although the build runner doesn't seem to produce any form of warning in logs (even with `--verbose`), I thankfully did see this warning in VS Code, which led me to the fix: 

<img width="754" alt="image" src="https://user-images.githubusercontent.com/3922667/129257927-d108f83b-b01a-4ff1-af7b-2cec30db93ff.png">

@vytautas-pranskunas- could you try this out?

**Comment by aboedo** [comment]
@vytautas-pranskunas- I actually misinterpreted what would happen with the import alias, I read [this PR](https://github.com/mobxjs/mobx.dart/pull/309) and assumed that it would work for all imports, but the mobx import itself doesn't actually get a prefix in the generated file. 

However if you add an import alias to `purchases`, in the generated file it does include the prefix. I'm not getting any warnings in my sample app when doing this, what message are you getting on `purchase.Product` there?

**Comment by vytautas-pranskunas-** [comment]
Hmm it looks like yesterday it was just IDE crying. Today I have tried to add cast to purchases and all is good.

**Comment by aboedo** [comment]
Thanks for the update! And I'm glad you brought this up. I'll add something to our docs to help folks if they run into something like it in the future.
