### ISSUE TITLE
MediaCodec discarded an unknown buffer

### ISSUE THREAD

**Issue by knightowlRaising** [RevenueCat/purchases-flutter#238]
While testing with Testing Card credentials the callback crashing the app with an error: MediaCodec discarded an unknown buffer

**Comment by aboedo** [comment]
Hi! Thanks for reporting. 
We need more information about this in order to reproduce the issue. 
Could you share debug logs, a stack trace, and the output of `flutter doctor`? 

At first glance, this seems very unlikely to be related to our SDK - we don't decode media. Do you have any other plugins in your project? Otherwise, could this crash be happening on the callback from when the test purchase is done?

**Comment by knightowlRaising** [comment]
It's working fine now, might be some OS-related issue. It didn't appear again. You can close this issue. Thanks~

**Comment by aboedo** [comment]
Thanks for reporting back! Closing now.
