### ISSUE TITLE
Android Billing Confirmation Issue - Couldn't find purchase lists, trying to find single data.

### ISSUE THREAD

**Issue by arodriguezgb** [RevenueCat/purchases-flutter#249]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
SDK is 3.4.5
Everything works on IOS, but android is not. Same code.

When the subscription is successful I get this message on the log.

W/BillingHelper( 5733): Couldn't find purchase lists, trying to find single data.

The subscription is working, but i cant get the confirmation working and it was working before. Im not really sure when it started malfunctioning, I noticed now because I am working on an event trigger based on the purchase confirmation.

1. Environment
In Pubspec file: purchases_flutter: ^3.4.5
```
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

• No issues found!
`
```
2. Debug logs that reproduce the issue
3. The only thing on the log is this 
```
`W/BillingHelper( 5733): Couldn't find purchase lists, trying to find single data.
W/[Purchases] - WARN( 5733): 🤖‼️ There's more than one sku in the PurchaseHistoryRecord, but only one will be used.
 `
```
3. Steps to reproduce, with a description of expected vs. actual behavior
This works perfectly on IOS, but on Android buying the item never returns a confirmation so I cannot trigger an event or close the page.Here is some code.
```
                             PurchaserInfo purchaserInfo =
                                await Purchases.purchasePackage(_packages[0]);

                            if (purchaserInfo != null) {
                              
                              var isPro = purchaserInfo
                                  .entitlements.all["Premium"]!.isActive;
                              
                              if (isPro) {
                                final Map eventValues = {"userId": _userId};

                                if (Platform.isIOS) {
                                  appsflyerSdk.logEvent(
                                      'inapp_purchase_ios', eventValues);
                                } else {
                                  appsflyerSdk.logEvent(
                                      'inapp_purchase_android', eventValues);
                                }                    

```
4. Other information (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**
Like I mentioned before this is not an issue on IOS as everything works fine. When the user purchases the subscription I get the confirmation, I trigger my event  and the close the current page. But on Android I get the issue I shared here.

**Comment by stwarwas** [comment]
I'm also experiencing a problem with the billing confirmation under Android.

As test user who performs a purchase I receive an email confirming that I purchased the subscription.

Short after I get another email telling me that the subscription was not confirmed.

As I understood from the documentation revenuecat should confirm it automatically. 

The observer mode is off.

Error code 2: "There was a problem with the Play Store"

**Comment by aboedo** [comment]
hi!! 👋 thanks for reporting, I'm going to try to reproduce and report back.

**Comment by officialFlutterDeveloper** [comment]
@aboedo   Purchases.addPurchaserInfoUpdateListener is not working for me 

im using the latest sdk 3.4.5

 im testing to get my grip on the package but im getting a little issues

basically I have one stful widget and in that widget I have an App bar and 1 button in centre 

in my INIT state I have used the following code

 **@override
  void initState() {


    Purchases.addPurchaserInfoUpdateListener((purchaserInfo) {
      activeSubscriptions = purchaserInfo.entitlements.active.values.toList();

      print(activeSubscriptions.length);
      print(purchaserInfo.activeSubscriptions.length);
      setState(() {
        color = activeSubscriptions.isEmpty || activeSubscriptions == null
            ? Colors.red
            : Colors.green;
      });
    });
    super.initState();
  }**



im trying to make appBar color change depending on subscription state

 when I make a purchase and I get the successful prompt the app bar goes green so this works exactly how I want but when the expiration time ends it does not go back to red UNTIL the state is set again

**Comment by aboedo** [comment]
hi everyone!! 
There seem to be a few different things going on in this ticket, so I'll address them one at a time: 

@arodriguezgb This message happens when you haven't added the email you're using in Google Play to the licensed testers list. [Here's our guide on getting that set up](https://docs.revenuecat.com/docs/google-play-store#create-a-test-user-and-configure-licensing-testing), let me know if that doesn't do the trick! 

@stwarwas that's correct, our SDK automatically acknowledges purchases. It sounds like there might be an issue with your Google Play Store configuration in the RevenueCat dashboard. Does the purchase show up there? (Remember to check "View Sandbox data" on the top right). If it' doesn't get registered at all, [here's our guide to setting up credentials](https://docs.revenuecat.com/docs/creating-play-service-credentials). If that doesn't help, would you mind opening up a separate ticket so we can track it there and figure out what's going on? 

@officialFlutterDeveloper and I continued the conversation on a [separate ticket](https://github.com/RevenueCat/purchases-flutter/issues/251) for their concerns, if there are any more related questions let's continue on that ticket.

**Comment by arodriguezgb** [comment]
@aboedo 
The account is on the licensed testers. 

I thought it could be the account at first but I tried different accounts on different phones and the same issue, the confirmation never happens.

The process was working fine and it stopped working, same code, nothing changed.

It doesn't work on debug, it doesn't work live. The confirmation just never happens. 

The app has been production for almost a year now, and it was working fine.

**Comment by aboedo** [comment]
@arodriguezgb Thanks for the quick response! 

Does the [MagicWeather](https://github.com/RevenueCat/purchases-flutter/tree/main/revenuecat_examples/MagicWeather) sample app work correctly for you on the same account? If you haven't yet, all you need to do to test it is to edit [constant.dart](https://github.com/RevenueCat/purchases-flutter/tree/main/revenuecat_examples/MagicWeather) to set up your API key and entitlement id. 

I just tested it and it works correctly on my account on `purchases_flutter` `3.4.5`. 

I'm asking to try to figure out whether the problem could be on the app or on the account.

**Comment by arodriguezgb** [comment]
I will try this today, however, there may be something because this was working on earlier versions of the plugin. 

Unless something changed in how things have to be done and I missed it.

**Comment by aboedo** [comment]
awesome, let me know how it goes!

**Comment by arodriguezgb** [comment]
@aboedo The subscription status on Weather app is Active.  However I mentioned before the subscription is working fine.

Like , if the user restarts the app after doing the subscription, the user will be subscribed.

This app does not cover this unless im doing something wrong.

The issue I am having is that after I successfully subscribe, revenuecat is not finding the premium entitlement right away so I can confirm the order and close the window etc.

**Comment by aboedo** [comment]
thanks for reporting back! A couple of questions: 

- Does the purchase show up in the RevenueCat dashboard? (Make sure to enable "View Sandbox Data"
- You probably already have, but just to cover all bases, have to double-checked that the entitlement identifier matches the value you set up in the RevenueCat dashboard? Are there any values in `purchaserInfo.entitlements.active`?

**Comment by arodriguezgb** [comment]
I am not sure if it shows there, but its definitely working.

When the subscription is successful on google's framework, I don't get the confirmation right away. But lets say if I close the app and open it again, I am subscribed. So it definitely works, 

but that's not the way it should work, the subscription confirmation should work right away to confirm isPRO like in the code I pasted above which is the one on the documentation 


And same thing on the second point, the identifier is is correct, its the same yes.  Right away entitlements.isActive does not show anything I believe because isPro is not working. But like i said, the sub worked fine, its just in that moment, if I close the app and open it again, when I check again for active entitlements its there and it says its Active.

the issue is here at the time of purchase.


```
  PurchaserInfo purchaserInfo = await Purchases.purchasePackage(package);
  var isPro = purchaserInfo.entitlements.all["my_entitlement_identifier"].isActive;
  if (isPro) {
    **// THIS IS NEVER BEING CALLED BECAUSE ISACTIVE IS NOT WORKING RIGHT AWAY**
}
```

**Comment by aboedo** [comment]
@arodriguezgb thanks for your patience on this one. And yes, what you describe is the expected behavior - isActive should be `true` for the entitlement that's coming from the `purchaserInfo` instance returned by `purchasePackage`. 

I haven't been able to reproduce the bug yet, though: I just tried this again on one of our sample apps, on 3.4.5, with the following code: 
<img width="557" alt="image" src="https://user-images.githubusercontent.com/3922667/135687950-a798f42c-0a26-4bcf-a768-a75383709002.png">
And I did go into `isPro` right away.
I'm not sure what might be happening for your case. 
Have you tried with other test users? 

Any chance that the code within `isPro` is being called, but it's not making the expected updates? I imagine you might have tested this already, but I'm trying to cover all bases.

**Comment by arodriguezgb** [comment]
@aboedo 
Yes , I have tried with other tests users. 

No , i have tried removing everything and just doing comments like you have there, but it does not get inside isPro. It doesnt get to the else either. 

Im not sure what can be causing this :(.

**Comment by aboedo** [comment]
@arodriguezgb Thanks for the update! I'm glad you figured this out! For what it's worth, we've been thinking about ways to make it more apparent when there's a problem like `setup` being called more than once, so that this kind of thing is less likely to happen. 

Don't hesitate to reach out again if you run into more issues in the future. 

Have a great day! 
Andy

**Comment by daniel-hopkins** [comment]
If anyone has a similar issue where ios is working, but not android. Perhaps you are sending your apple apiKey to google like I was :(. Now I'm checking platform and it works perfectly.
```
if (Platform.isAndroid) {
      apiKey = Config.revenueCatAPIKey_google;
    } else if (Platform.isIOS) {
      apiKey = Config.revenueCatAPIKey_apple;
    }
```
