### ISSUE TITLE
Billing is not available in this device. DebugMessage: Google Play In-app Billing API version is less than 3. ErrorCode: BILLING_UNAVAILABLE

### ISSUE THREAD

**Issue by abeyshiferaw0** [RevenueCat/purchases-flutter#263]
Billing is not available in this device. DebugMessage: Google Play In-app Billing API version is less than 3. ErrorCode: BILLING_UNAVAILABLE

**Comment by vegaro** [comment]
Uploading to a track would solve issues with purchasing, not with not being available to connect to the Google Play In-app Billing API. I assume you are but are you logged in to Play Store in the device you are using? The main two reasons why this error is displayed is because either the emulator image doesn't have the Play Store installed or because you're not logged in.

**Comment by codykerns** [comment]
I'm going to go ahead and close this for now. If you're able to upgrade to the latest SDK and confirm you are logged into the Play Store, and are still encountering this issue, please re-open and we'll take a look!

**Comment by abeyshiferaw0** [comment]
Sorry for not following up on this issue for this long  and yes i was getting this issue after i have done every thing what the documentation says , but there wasn't a problem with revenue cat  package or google billing service. it was because i was living in a country that google billing doesn't support, the error "Google Play In-app Billing API version is less than 3" is very vague and does't explain the real issue.   

but by chance if this issue happens to anyone, the only fix i found in the whole internet is to
1.remove all google accounts from device
2.enable vpn in united states 
3.clear google play service and google play data from settings
4.create a new fake google account with the same device, to develop app with in app purchase or revenue cat package
