### ISSUE TITLE
Know details about the user purchase: product name and price

### ISSUE THREAD

**Issue by rocboronat** [RevenueCat/purchases-flutter#316]
Hello! I've seen that `restoreTransactions()` returns a list of old purchases with their bundle and their purchase date, but I don't have neither the price the user paid or the name of the product he bought.

I'm trying to achieve doing this screen, possible with the data both Google Play and the App Store share 👇 

<img height="400" src="https://user-images.githubusercontent.com/456499/153018758-e21f6ee3-2a89-46b1-840e-acbb1175953f.png"/>

But right now, the only data I have is this 👇 

![image](https://user-images.githubusercontent.com/456499/153021421-b40d904d-aa94-48ba-9cfa-d3e362047efb.png)

Maybe I'm wrong and I'm looking for the data in the wrong place?

**Comment by rocboronat** [comment]
Ohhh it's something. But as the official Flutter IAP package gave us the price the user paid, I expected you to be able to offer it. Any chance to have that price added to your roadmap?

And about the screen I'm trying to do,  will I be able to show all the payments the user made?

Thanks a lot for your support 😊

**Comment by codykerns** [comment]
Hey @rocboronat!

Since Apple and Google don't expose the price paid for transactions, it's likely that the price from Flutter IAP is actually the _product_ price and not the _transaction_ price that the user actually paid. [I couldn't find](https://github.com/flutter/plugins/blob/7686be7ecbe1cc049423715b5e2d897cb63a43c1/packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.dart) a reference to price paid for purchases in their documentation.

In general, we don't currently have prices and listing transactions in PurchaserInfo on the roadmap because of privacy concerns - they would have to be publicly accessible and so we opt for just including subscription status in our responses for now. I'd recommend forwarding your customers to the Play Store for details about their subscriptions/purchases.

**Comment by rocboronat** [comment]
Hum... I have sworn the first versions of the Flutter's IAP plugin had that original price. Now, I'm rechecking a issue I opened in Flutter's repo, and they gave me a solution, but it doesn't work. If you are curious about it, check it: https://github.com/flutter/flutter/issues/98120
