### ISSUE TITLE
Breaking change not treated as breaking change

### ISSUE THREAD

**Issue by Lootwig** [RevenueCat/purchases-flutter#318]
Somewhere between 3.8.0 and 3.9.3, the "IntroductoryPrice.periodUnit" field was re-typed from `String` to the `PeriodUnit` enum, and the entire class moved into a different location.

This is a **breaking change** which breaks builds without updating code and should be reflected by

a) [bumping the major version of the package](https://semver.org/) and
b) [highlighting this in the changelog](https://pub.dev/packages/purchases_flutter/changelog)

**Comment by joshdholtz** [comment]
@Lootwig My apologies on this! It looks like this was missed when considering the version bump and changelog. We 100% should bumped the version or called it out in the changelog. 

It appears this happened in https://github.com/RevenueCat/purchases-flutter/pull/270 which was included in `3.9.1`. Since its too late to update the changelog, I'll make sure that we will update the changelog appropriately. 

I do want to through the diff to make sure there aren't any other types that we missed that also need calling out in the changelog.

I appreciate you letting us know and we will get this updated as soon as we can! Thank you 😊

**Comment by beylmk** [comment]
Hey @Lootwig ignore the bot! We are in the process of releasing the fix. I'll post back here when that's done!

**Comment by beylmk** [comment]
Hey @Lootwig all fields should be added back in https://github.com/RevenueCat/purchases-flutter/releases/tag/3.9.4! I'm going to close this ticket for now, but feel free to re-open if you notice anything else. Thanks again for raising this to our attention.
