### ISSUE TITLE
[4.0.0-rc.1] User cancelled crash

### ISSUE THREAD

**Issue by MinseokKang003** [RevenueCat/purchases-flutter#403]
After updating from 4.0.0-beta.1 to 4.0.0-rc.1, 
app crashes(unhandled) when user cancels payment process.

The issue is resolved when downgrading back to 4.0.0-beta.1.

Can you please check if the issue is reproducible?

**Comment by samry** [comment]
Experiencing the same issue, except I'm on 4.0.0-beta.1.

The device (NOT a simulator) is an iPhone XR with iOS 15.5.

Logs below/:

`-[__SwiftValue _fastCStringContents:]: unrecognized selector sent to instance 0x283330cf0
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__SwiftValue _fastCStringContents:]: unrecognized selector sent to instance 0x283330cf0'
*** First throw call stack:
(0x193901288 0x1ac5fb744 0x1939defc4 0x193895e98 0x193894f70 0x19852fd58 0x19852ff0c 0x1985300f0 0x197fc1d1c 0x10619096c 0x106190770 0x106184cd8 0x106184240 0x10685022c 0x1068b7454 0x1068b74b0 0x193566e6c 0x193568a30 0x193576f48 0x193576b98 0x1938b9800 0x193873704 0x193886bc8 0x1af9ba374 0x1961f6648 0x195f77d90 0x104d7c3a0 0x104fbdce4)`

**Comment by MinseokKang003** [comment]
@samry 's logs are the same crash logs I encountered.

I'm on iPhone13 Pro(Real Device) with iOS 15.5.

**Comment by beylmk** [comment]
Hey all,

Thanks for reporting... I'm looking into this today

**Comment by beylmk** [comment]
We've identified the issue and are working on a fix...I'll post back here when it's out. Thank you for your patience!

**Comment by beylmk** [comment]
Hey all, please see [4.0.0-rc.2](https://github.com/RevenueCat/purchases-flutter/releases/tag/4.0.0-rc.2) for the fix. Feel free to re-open this issue if needed.

**Comment by NachoSoto** [comment]
Proper fix for this is https://github.com/RevenueCat/purchases-ios/pull/1841
We will update [PurchasesHybridCommon](https://github.com/RevenueCat/purchases-hybrid-common) and then we can re-enable SK2 here.
