### ISSUE TITLE
Errors running Pod Install

### ISSUE THREAD

**Issue by CarsonC01** [RevenueCat/purchases-flutter#41]
Every time I add this package to a Flutter project and then try to run it, I get a Pod error. I've tried going back to a completely new Flutter app and running it and it still errors. 

Here is the error message:

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11 Pro.

**Comment by vegaro** [comment]
Hi @CarsonC01.

Our SDK requires iOS 9.0+. Looking at our example, we have defined the ios platform as 9 in the Podfile https://github.com/RevenueCat/purchases-flutter/blob/master/example/ios/Podfile.

It looks like Flutter doesn't add this automatically

**Comment by Paul-Todd** [comment]
Hi,

Any idea when you can push this fix into a new version? Its a blocker for me

**Comment by aboedo** [comment]
@Paul-Todd I'm sorry for the inconvenience. Like Cesar said, it looks like the issue is that Flutter doesn't add the minimum deployment target automatically. So it'll default to an old version that's unsupported by RevenueCat and thus the error message. 

You can easily get around this in your project by going editing `ios/Podifle`, and adding the minimum deployment target: add the following line
```
platform :ios, '9.0'
```
Cocoapods (which Flutter is using for iOS dependencies) auto-generates that line but leaves it commented out. 

You need target version 9.0 or higher for RevenueCat. 
I don't think there's much that we can do for the plugin to tell Flutter to automatically set a deployment version, since deployment versions should be determined by apps and not plugins. 
I'll still check to see if anything can be done, and we can at least improve our documentation to make this step clearer.

**Comment by Paul-Todd** [comment]
Thanks, that fixed it!

**Comment by CarsonC01** [comment]
Many thanks

Yes that fixed it.

Sent from my iPhone

On May 7, 2020, at 1:15 AM, Cesar de la Vega <notifications@github.com> wrote:

﻿

Hi @CarsonC01<https://github.com/CarsonC01>.

Our SDK requires iOS 9.0+. Looking at our example, we have defined the ios platform as 9 in the Podfile https://github.com/RevenueCat/purchases-flutter/blob/master/example/ios/Podfile.

It looks like Flutter doesn't add this automatically
