### ISSUE TITLE
How to set auto-renewable subscription?

### ISSUE THREAD

**Issue by Medrov** [RevenueCat/purchases-flutter#58]
Perhaps. this question is so dumb, but I really want to know how can I use auto-renewable subscription, I saw your article in the site about restoring, but I couldn't understand how to implement it.

**Comment by aboedo** [comment]
Hi! 

For a good intro to auto-renewable subscriptions, check out [our QuickStart page](https://docs.revenuecat.com/docs/getting-started) 

You can also find a lot of [info in our docs here](docs.revenuecat.com).

We reserve GitHub issues for bug reports, but if you need any help setting up you can reach our support team at [our support site](support.revenuecat.com). I'm going to close this issue because of that, but take a look at the docs and reach out to support if you need any help!
