### ISSUE TITLE
Purchases.addCustomerInfoUpdateListener not called back

### ISSUE THREAD

**Issue by Alisofin** [RevenueCat/purchases-flutter#677]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

# ‼️ Required data ‼️ #
**Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

There are a lot of things that can contribute to things not working. Having a very basic understanding of your environment will help us understand your issue faster!

## Environment ##
- [x] Output of `flutter doctor`
Flutter is already up to date on channel stable
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (il y a 6 jours) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
MacBook-dAlain:ios alain$ cd ..
MacBook-dAlain:birdy_cam alain$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" in System Settings to install updates
MacBook-dAlain:birdy_cam alain$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.75.1)
[✓] Connected device (4 available)
    ! Error: Apple Watch de alain needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)
[✓] HTTP Host Availability

• No issues found!

- [x] Version of `purchases-flutter`: 4.11.3
- [x] Testing device version e.g.: iOS 15.5, Android API 30, etc.: iOS 16.4.1 on real device
- [x] How often the issue occurs- every one of your customers is impacted? Only in dev? It occurs systematically on dev mode. The app is not published yet.
- [x] [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue: none
- [x] Steps to reproduce, with a description of expected vs. actual behavior
**Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

## Describe the bug ##
The Purchases.addCustomerInfoUpdateListener handler is never called back. Especially, when a subscription is ending, I would expect to get a call back and manage the end of the subscription in the App but it doesn't happen. Furthermore, if the App calls Purchases.getCustomerInfo() the information of subscription changed is not updated, as if purchases-flutter answer was based on a cache information, not updated from the store.
Many thanks for your support.

## Additional context ##
I use Flutter

**Comment by tonidero** [comment]
Hi @Alisofin. We do cache the customer info in the device. However, we initiate a cache refresh in the following situations as long as 5 minutes have passed since the data was cached:
- The SDK was configured, like if the app was restarted. This will happen even if the 5min have not passed.
- The app went to foreground from background
- You call `getCustomerInfo`
- The user purchased something.

After those situations, as long as the customer info information changed, you should receive the latest updated data in the listener. Note this means we won't automatically call the listener as soon as a subscription renews/ends, but the next time one of the above situations happens.

I just tested the Flutter SDK in iOS using our sample app and I was able to receive updates. Do you think you might be calling `getCustomerInfo` within that 5 minute time frame? If that's not your issue, could you send some logs to help us debug the issue?
