### ISSUE TITLE
Offline Support for Entitlements

### ISSUE THREAD

**Issue by erluxman** [RevenueCat/purchases-flutter#69]
Our app can be used offline and user has a certain quota on how many records he can create. 

So we need a way to fetch Entitlement info offline as well (the one fetched recently) so that we can tally user's quota with what entitlement is available to them. 

Is there any way to do this already?

**Comment by aboedo** [comment]
I'm assuming that by Entitlements, you mean the entitlements that the user has purchased, which would be inside the `purchaserInfo` object. Let me know if I missed something there. 

The SDK will cache `purchaserInfo` for only 5 minutes. The thinking is that since `purchaserInfo` could change at any time outside the app, we want it to be up to date. 
When you call `getPurchaserInfo`, if the local cache is outdated (i.e.: it's been more than 5 minutes since the last refresh), it will return the cached information + trigger a refresh that will come up in a callback. 
This method should still work without connectivity, since you'll receive the latest cache information. 
Does this cover your case?

**Comment by erluxman** [comment]
Will get back to you with what I find, I might have missed something.

**Comment by erluxman** [comment]
I can confirm that there is offline support which I was missing for some reasons.

**Comment by armandojimenez** [comment]
Question, what if the user cancel the subscription and only opens the app for a month with no connectivity, will still return as active from the cache??

**Comment by vegaro** [comment]
@armandojimenez that's correct. Most apps require some sort of network connectivity to offer their functionality, so the way the system is designed works for most apps.

**Comment by armandojimenez** [comment]
I understand. My app does not need Internet connection, it just unlock stuff in the app, how can I deal with this? Maybe checking if has the entitlement but also checking expiring date? is there a way to know if the cache is old or outdated? I can see it on the logs

**Comment by vegaro** [comment]
`PurchaserInfo` has a `requestDate` property that you can check to block the user if the cache is too old and force them to connect. I think that could work in your case?

**Comment by armandojimenez** [comment]
Yes that can work, thanks!
