### ISSUE TITLE
Pass subscription period to Flutter

### ISSUE THREAD

**Issue by IchordeDionysos** [RevenueCat/purchases-flutter#7]
It's often useful to get the subscription period to display it or calculate various things before displaying it.

**Comment by davidBarbieri** [comment]
Looking forward for this feature as localization can be a pain otherwise

**Comment by britannio** [comment]
Can this feature be expected in the near term? The docs state that only supporting a fixed number of products isn't the best practice. https://docs.revenuecat.com/docs/displaying-products#best-practices

**Comment by vegaro** [comment]
Localization could be achieved by using the offerings system and checking the type for the packages (https://docs.revenuecat.com/docs/displaying-products#displaying-packages, https://github.com/RevenueCat/purchases-flutter/blob/develop/lib/package_wrapper.dart#L32).

I will add this to our backlog to discuss it with product, but I can't promise this will be done.

I am going to close this issue since it's a feature request more than an issue with the plugin.
