### ISSUE TITLE
I am getting empty offerings list on iOS

### ISSUE THREAD

**Issue by erluxman** [RevenueCat/purchases-flutter#71]
Currently, I am trying to setup RevenueCat on iOS and I have added 

AppBundle ID, TunesConnect App-Specific Shared Secret, Didn't add p8 key as it's for iOS offers. 

Also added Apple Server Notification URL to AppStore connect  

But I am getting an empty offerings list in iOS.

**Comment by aboedo** [comment]
Hi! 👋 

This looks like a configuration issue. We try to reserve GitHub issues for bug reports only. 

Would you mind [contacting our support](https://support.revenuecat.com) for your case? They're better equipped to help you figure this out.

**Comment by adiltirur** [comment]
I had the same issue now, but it looks like it works in a physical device but not in simulator in my case

**Comment by erluxman** [comment]
I was testing in Real device

**Comment by vegaro** [comment]
Empty offerings or products is due to a configuration issue. Please find more help on how to fix this particular issue here https://spectrum.chat/revenuecat/general/why-are-my-products-and-offerings-empty~2aef23bf-1bc2-4fdd-8b4c-f51a8a0463ad.

I am going to close this since we are trying to keep GitHub issues only for bug reports only.
