### ISSUE TITLE
Expose 'purchaseId'

### ISSUE THREAD

**Issue by kinex** [RevenueCat/purchases-flutter#72]
In my app I don't want to allow user to sign in with several Firebase accounts and add data with each of them. This seems to be impossible to fix if using RevenueCat because subscriptions cannot be identified.

Current API is missing a method for getting the purchase ID (also called "transaction ID" or "order ID"). Without this id it is impossible for example to limit a subscription to a single Firebase account. I am sure there are also other uses for this id.

In Android this can be used: https://developer.android.com/reference/com/android/billingclient/api/Purchase#getOrderId()

In iOS this would be probably the best option: `web_order_line_item_id` (https://developer.apple.com/documentation/appstorereceipts/responsebody/latest_receipt_info). There is also `transaction_id` available but it changes every time when user restores purchases or when the subscription is renewed. Other option could be to use `original_transaction_id`, but be aware of one strange issue I have noticed earlier: `transaction_id` or `original_transaction_id` read from device may be different compared to those received from AppStore receipt validation server.

**Comment by vegaro** [comment]
Hi @kinex. I am not sure I understand what issue you are facing. What do you mean with "subscriptions cannot be identified"? By default, RevenueCat will not let you reuse a subscription from an App or Play Store account that already has that subscription active. You can read more about it here https://docs.revenuecat.com/v2.0/docs/user-ids#sharing-subscriptions-across-store-accounts

**Comment by kinex** [comment]
Hi @vegaro, In the device where the purchase was made the subscription is always active no matter which Firebase account the user uses. That is the problem. Currently subscription cannot be associated with a specific Firebase account since you don't provide the purchase ID. 

I need the purchase ID to store in Firebase database a map of <userId, purchaseID> values. This way I can verify in login if the subscription is already associated with a different account and prevent user from signing in with multiple accounts.

Another use case for the purchase ID is customer support. If user has a problem with the subscription or if we wants a refund, I need to know the purchase ID. I could show the ID in my app UI.

**Comment by meyerjoe** [comment]
The same issue is already described here https://docs.revenuecat.com/discuss/5c056b245991b401c7ea8f3d and here https://stackoverflow.com/questions/55343004/ios-firebase-auto-renewable-subscriptions?rq=1.

It is not obvious to me either how these cases can be solved with the current API of RevenueCat. The whole "alias" and "identify" stuff seems rather counter-productive, since it helps mixing up accounts which should not be linked together. allowSharingAppStoreAccount seems to be honoured in the entitlement, but doesn't seem to be honoured when trying to make a purchase (no error message or exception when e.g. purchasing a 3-month subscription with new userId, when the app store user purchased already a monthly subscription with another userId). Ideally, I don't want to let the user run into an exception, but be able to determine beforehand if the userId in my app is already uniquely linked to the subscription of an app store user.

**Comment by meyerjoe** [comment]
... or rather vice versa: if the current app store user is already linked to an app user (probably through original_transaction_id)

**Comment by vegaro** [comment]
> In the device where the purchase was made the subscription is always active no matter which Firebase account the user uses.

Are you calling `createAlias`? You should probably just be calling `identify`. This way, since you are using Firebase IDs, and `allowSharingPlayStoreAccount` is set to false by default, the subscription will be attached to the first Firebase account that posted that purchase to RevenueCat, and the following users that try to post the same purchase to our backend will get an error. 

We still have `createAlias` in the API because some people need it for very particular implementations, but we modified `identify` some months ago to be more intuitive and most of the developers shouldn't be calling `createAlias` directly. Please note that the answers found on https://docs.revenuecat.com/discuss/5c056b245991b401c7ea8f3d are from before we modified identify and createAlias and the behavior has changed.

**Comment by kinex** [comment]
I am not calling `createAlias`, I only call `identify`. Actually I thought `identify` can be called from the device where the purchase was made to change ("rename") the `AppUserId` even after the purchase was made. Is it mentioned in your doc that subscription is attached to the current `AppUserId` and cannot be changed later? Maybe I have missed it.

But I am not sure if this solves the issue. I see at least these problems:
1. Your doc says "If two different App User IDs try to restore transactions from the same underlying store account (Apple or Google) RevenueCat will create an alias between the two App User IDs and count them as the same user going forward.". So I cannot prevent two or more Firebase accounts sharing the same subscription anyway because user can restore the subscription with any Firebase account?
2. User can purchase subscription A using Firebase account 1 and then purchase subscription B using Firebase account 2. This is also unwanted behavior. User should be allowed to purchase only one subscription.

**Comment by vegaro** [comment]
> Your doc says "If two different App User IDs try to restore transactions from the same underlying store account (Apple or Google) RevenueCat will create an alias between the two App User IDs and count them as the same user going forward.". So I cannot prevent two or more Firebase accounts sharing the same subscription anyway because user can restore the subscription with any Firebase account?

Since you are using Firebase IDs when configuring the SDK, you don't need to add a restore function. By default, restore does an alias, which will connect Account A and Account B via the shared App Store Account. Usually, if purchases are only made when a user has an account (the Firebase account), a restore button is not needed. Apple and Google just dictate that you have some way to restore purchases, having an account system satisfies that.

> User can purchase subscription A using Firebase account 1 and then purchase subscription B using Firebase account 2. This is also unwanted behavior. User should be allowed to purchase only one subscription.

Since both Firebase account 1 and 2 are using the same App Store account, Apple won't let them purchase the same subscription a second time. Also if `allowSharingStoreAccount` is set to `false` (which should be since you are configuring the SDK with a Firebase account and `false` is the default), RevenueCat will give an error and won't let Firebase account 2 own a receipt that's already attached to Firebase account 1 in the case they purchase another subscription.

I think this is mostly an edge case and very few users will face this. User B will be asked for the App Store/Play Store password before making a purchase. And even if they manage to make the purchase, you can display an error message after you get the error from RevenueCat indicating the another user owns the purchase.

**Comment by kinex** [comment]
I know it won't let you purchase the same subscription (OS prevents that, not RevenueCat). But with subscription A and subscription B I meant different subscriptions. There can be for example a monthly and a yearly subscription and some other subscription types. For example we have 4 different monthly subscription types from which only one should be active at a time. 

I tested this in Android I was able to purchase two different subscriptions using two different Firebase accounts in the same device. No passwords were asked and not any errors were returned by RevenueCat. I also checked from the Play Store app that there were two active subscriptions. If you have defined subscription groups in AppStore, an automatic subscription upgrade/downgrade would happen if user purchases another subscription type using Firebase account 2. This would be also very confusing.

**Comment by rkotzy** [comment]
Going to close this out since it isn't a Flutter SDK issue exactly. We are planning some improvements to identity in RevenueCat that will give developers more control over how aliases are handled which could help out here. 

Definitely don't hesitate to contact our support team through the [Help Center](https://support.revenuecat.com/hc/en-us) if there's anything we can clarify.
