### ISSUE TITLE
Expose the purchase verification data in Flutter SDK

### ISSUE THREAD

**Issue by rahulraj64** [RevenueCat/purchases-flutter#73]
I'm planning to migrate to RevenueCat. Currently using the official Flutter InApp purchase plugin, which provides the verification data. On Android, this is the **Purchase Token** & on iOS, this is the **Purchase Receipt**. I'm sending those to the server for validation. 

Searching through the documentation, I could not find the details to get the verification data through the SDK, once a purchase is made. This is very important for someone who is migrating to RevenueCat since they need to send a copy of the receipt to their own server as well, for backward compatibility.

**Comment by meyerjoe** [comment]
I second that.

**Comment by vegaro** [comment]
We don't have plans for now on exposing these in the SDK, since the purpose of RevenueCat is to abstract this complexity from the developers. We have a guide https://docs.revenuecat.com/docs/migrating-existing-subscriptions that could help you setting up a migration path with backward compatibility. 

You can also keep using the system that you already have in place to access the purchase tokens and the receipts if you really need to do that. Or you can also use us in observer mode https://docs.revenuecat.com/docs/migrating-existing-subscriptions#use-revenuecat-backend-only-observer-mode if you want to keep the system you have in place and use the RevenueCat SDK to get access to the advanced charting, webhooks, and attribution that we can provide.

If you ever want to migrate away from RevenueCat, we can also export all of your users' receipts so you can import them into whatever solution you're migrating to.

**Comment by rahulraj64** [comment]
Hi, @vegaro Thanks for your input.
Exposing the receipt or token does not prevent the abstraction of complexity. But it provides an extra option for the users to save the data themselves if they want to. It really improves the flexibility of the SDK. I have migrated to RevenueCat, but still, I need to maintain the old InApp library for the purpose of receiving the token. This will result in maintaining two libraries for a single payment solution, which is frustrating. Also, may lead to side effects. Rather than proactively closing this, I request you to present this in your next feature meeting.
Thanks.

**Comment by vegaro** [comment]
I did make a Feature Request regarding this for the product team to review. You can request future requests here https://support.revenuecat.com/hc/en-us/articles/360046422033-Feature-Requests. That link is better since it allow us to keep better track of the features that are being requested across all platforms.

I am intrigued about when you said: "they need to send a copy of the receipt to their own server as well, for backward compatibility."

What do you mean with backward compatibility?
