### ISSUE TITLE
[Android] couldn't find product error

### ISSUE THREAD

**Issue by EliasDeuss** [RevenueCat/purchases-flutter#80]
Getting this error when trying to purchase a in app purchase.

All the products keys match exactly and it still doesn't work.

![Screenshot_20200701-181542.png](https://user-images.githubusercontent.com/13773566/86305807-6ffda000-bbc7-11ea-871a-f78abb7d66e5.png)

**Comment by vegaro** [comment]
Hi @EliasDeuss .

Are you calling `purchaseProduct` passing the `type` parameter?

```
Purchases.purchaseProduct("tieronetip", type: PurchaseType.inapp);
```

`purchaseProduct` and `getProducts` require that `type` to be passed if the product is an INAPP, only in Android. We know it's confusing (the docs are probably also not helpful), so we are going to be removing this parameter in the future to make it simpler.

Sorry you're facing these issues.

**Comment by panalgin** [comment]
Hi, I have an unreleased app on google play store, I have all my subscription/products as "Active" status on Google Play Console.
I also correctly configured my account on RevenueCat, setup the entitlements, offerings and products correctly. 

I confirm that by doing this,
`offerings = await Purchases.getOfferings();`

I get all products I configured as per to my expectation

However when I do:
`PurchaserInfo purchaserInfo = await Purchases.purchaseProduct(productToPurchase.identifier, type: PurchaseType.inapp);`

I face with product not found error. Is this because I don't have a released/appropriate apk on Google Play Console? I doubt this is the reason though. 

I double checked my product identifiers between PlayConsole and RevenueCat, all seems correct and at the initialization of the Flutter app, I clearly see that SkuDetails are properly fetched from the Google side.

What might be the reason?

Thanks

**Comment by panalgin** [comment]
Sorry, further investigation has shown that I receive an 

> The product is not available for purchase.
with error code 5.

I guess this is related to some configuration I should do on Play Console?

**Comment by vegaro** [comment]
> Is this because I don't have a released/appropriate apk on Google Play Console? I doubt this is the reason though.

@panalgin I believe this is the reason, you need to release the app to a closed track and add the logged in user in your phone as a tester for that track. The logged in user also needs to be a license tester. 

There is a section in our docs that will guide you through this process https://docs.revenuecat.com/docs/google-play-store

I hope that helps :)

**Comment by panalgin** [comment]
> > Is this because I don't have a released/appropriate apk on Google Play Console? I doubt this is the reason though.
> 
> @panalgin I believe this is the reason, you need to release the app to a closed track and add the logged in user in your phone as a tester for that track. The logged in user also needs to be a license tester.
> 
> There is a section in our docs that will guide you through this process https://docs.revenuecat.com/docs/google-play-store
> 
> I hope that helps :)

Thanks so much, I did exactly what you have suggested and it now works as expected!

cheers
