### ISSUE TITLE
Failed to launch billing intent.

### ISSUE THREAD

**Issue by NiamhG** [RevenueCat/purchases-flutter#87]
**Describe the bug**

Hi,

I am trying to setup RevenueCat (v1.2.1) for the first time with the flutter SDK  on an android phone (real phone, not simulator). I have initialised Purchases, and then I am trying to run the below code:

```
  Offerings offerings = await Purchases.getOfferings();
  final package = offerings.current.monthly;
  PurchaserInfo purchaserInfo = await Purchases.purchasePackage(package);
```

The offerings and package are found correctly, but I am getting the error:

> There was a problem with the Play Store. Error updating purchases. DebugMessage: Service connection is disconnected.. ErrorCode: SERVICE_DISCONNECTED.

1. Environment
    1. Platform: Android
    2. SDK version: 1.17.5 
    3. OS version: [9.1]( https://consumer.huawei.com/uk/emui-9-1/)
    4. XCode/Android Studio version:  Android Studio 3.6.3
    5. How widespread is the issue. Percentage of devices affected. - Only tried on the one.
2. Debug logs
<details>
D/[Purchases] - DEBUG( 4501): Vending offerings from cache
D/[Purchases] - DEBUG( 4501): purchase started - product: SkuDetails: {"skuDetailsToken":"AEuhp4K1KQ9kg9mW9yFrVeFD9560PXb-YeFxNzsLTokzellOnNRlKF8hHap0aU9VI9wu","productId":"pro_version_subscription","type":"subs","price":"£2.39","price_amount_micros":2390000,"price_currency_code":"GBP","subscriptionPeriod":"P1M","title":"Pro version subscription","description":"Unlocked the pro version by paying via subscription"} - offering: default
D/[Purchases] - DEBUG( 4501): Making purchase for sku: pro_version_subscription
W/BillingClient( 4501): Exception while launching billing flow: ; for sku: pro_version_subscription; try to reconnect
D/[Purchases] - DEBUG( 4501): BillingWrapper purchases failed to update. DebugMessage: Service connection is disconnected.. ErrorCode: SERVICE_DISCONNECTED.null
W/[Purchases] - INFO( 4501): Error updating purchases. DebugMessage: Service connection is disconnected.. ErrorCode: SERVICE_DISCONNECTED.
E/[Purchases] - ERROR( 4501): There was a problem with the Play Store. | Error updating purchases. DebugMessage: Service connection is disconnected.. ErrorCode: SERVICE_DISCONNECTED.
W/[Purchases] - INFO( 4501): Failed to launch billing intent. DebugMessage: Service connection is disconnected.. ErrorCode: SERVICE_DISCONNECTED.
</details>

I'm not sure if this is a bug, or an issue with how I have set it up. the fact I am able to get the offerings and package tell me that I must have done that correctly.

**Comment by vegaro** [comment]
Thanks for opening this @NiamhG 

It is actually the first time I see something like this 🤔  I assume the purchase dialog doesn't show up right? It looks like there might be an exception when calling `billingClient.launchBillingFlow` internally.

How are you setting up the plugin? Can you send us a snippet so that we can replicate it? I am mostly interested in the Activity where  you register the plugin. Something similar to https://github.com/RevenueCat/purchases-flutter/blob/develop/example/android/app/src/main/java/com/revenuecat/purchases_flutter_example/EmbeddingV1Activity.java#L13

Looking at this Stackoverflow post https://stackoverflow.com/questions/55769812/android-billingclient-error-exception-while-launching-billing-flow-for-sku, it looks like there might be some issue with the context we are passing the Google BillingClient in this line https://github.com/RevenueCat/purchases-flutter/blob/develop/android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java#L84

**Comment by NiamhG** [comment]
So it seems adding that line in the `MainActivity` made it work ! (Or at least now it opens the dialog with `This version of the application is not configured for billing`, but that's another thing).

Just to see where I was being stupid, could you show me where it was said to add that to the MainActivity? I couldn't see it in the [pub.dev](https://pub.dev/packages/purchases_flutter), or the [flutter quickstart](https://docs.revenuecat.com/docs/flutter)

**Comment by vegaro** [comment]
So, if adding that line means that it started working, I think we can assume that your app was not registering the plugin. Are you using the new FlutterActivity (`io.flutter.embedding.android.FlutterActivity`) or the old one pre 1.12 (`io.flutter.app.FlutterActivity`)? 

From https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects#full-flutter-app-migration:
> Remove the body of your android/app/src/main/java/[your/package/name]/MainActivity.java and change the FlutterActivity import. The new FlutterActivity no longer requires manually registering your plugins. It will now perform the registration automatically when the underlaying FlutterEngine is created.

The link I sent you (https://github.com/RevenueCat/purchases-flutter/blob/develop/example/android/app/src/main/java/com/revenuecat/purchases_flutter_example/EmbeddingV1Activity.java#L13) uses the old one, that's why we add the plugin manually, but in the new FlutterActivity (`io.flutter.embedding.android.FlutterActivity`) the plugins get registered automatically. Maybe you are using the old FlutterActivity but for some reason the contents are empty?

**Comment by NiamhG** [comment]
Ah yep you are correct. Not sure how I missed that I needed to migrate, haven't run into any issues with anything else I'm using!

Thanks again for your time and help.

**Comment by burakcbdn** [comment]
Same here!

**Comment by beylmk** [comment]
Hey @burakcbdn, sorry you're experiencing this! If you've read through the conversation above and are still having trouble, could you please open a new issue with more details and your debug logs?

**Comment by burakcbdn** [comment]
I opened question on stackoverflow and revenuecat community here are the
links:

https://stackoverflow.com/questions/68665011/revenuecat-storeproblem-when-trying-to-purchase-product

Flutter no problem with fetching products but I cannot purchase |
RevenueCat Community
<https://community.revenuecat.com/general-questions-7/flutter-no-problem-with-fetching-products-but-i-cannot-purchase-246>

beylmk ***@***.***>, 5 Ağu 2021 Per, 23:58 tarihinde şunu
yazdı:

**Comment by burakcbdn** [comment]
I opened question on stackoverflow and revenuecat community here are the links:

https://stackoverflow.com/questions/68665011/revenuecat-storeproblem-when-trying-to-purchase-product

https://community.revenuecat.com/general-questions-7/flutter-no-problem-with-fetching-products-but-i-cannot-purchase-246

**Comment by burakcbdn** [comment]
Any updates? @beylmk

**Comment by beylmk** [comment]
@burakcbdn can you please provide full debug logs from app launch through when you try to make a purchase? to turn them on, call purchases.setDebugLogsEnabled(true).
