### ISSUE TITLE
The await for CustomerInfo customerInfo = await Purchases.purchasePackage(myProductList[index]); never completed; MagicWeather example, v.6.3.0

### ISSUE THREAD

**Issue by FuadEfendi** [RevenueCat/purchases-flutter#875]
iPhone 15 Pro Max simulator
iOS 17.0
purchases_flutter: ^6.3.0
MagicWeather official example

I configured MagicWeather official example with my Apple Store API key (taken from RevenueCat AppStore configuration). Configured In-App Purchase, monthly subscription; configured RevenueCat. Added some debug "print" messages to ensure Purchases.purchasePackage() method call will indeed return. This method call never returns.

1. Click on "Change the Weather" opens "paywall" widget with correct price shown, and "terms and conditions" footer.
2. Click on the product item in the list (and I have single product only) will popup iOS username/password screen, "Sign in with Apple ID"
3. After authentication, I can "purchase" chosen product, using iOS "Sandbox" native widget (in my case, clicking "Subscribe" button triggers "Enter password to authorize this transaction")
4. After "purchase" it returns to "paywall" screen, and after few seconds delay it returns back to iOS "purchase product" widget, although I don't click anything
5. i**n a loop...**

And the `Purchases.purchasePackage(myProductList[index]); `method call never returns; I added debug message after it to verify.

To follow current README file format, this is what **expected**:

> Example Flow: Purchasing a Subscription
> 
> 1. On the home page, select **Change the Weather**.
> 2. On the prompted payment sheet, select the product listed.
> 3. On the next modal, select **Subscribe**.
> 4. On the next modal, sign in with your Sandbox Apple ID.
> 5. On the next modal, select **Ok**.
> 6. Return to the home page and select **Change the Weather** to see the weather change!
> 

And this is **actual behavior**:

1. On the home page, select **Change the Weather**.
2. On the prompted payment sheet, select the product listed.
3. On the next modal, select **Subscribe**.  [UNEXPECTED: wait 3-5 seconds!!!]
4. On the next modal, sign in with your Sandbox Apple ID.
5. On the next modal, select **Ok**. [UNEXPECTED: there is no **Ok**]
6. After short **Done** modal, we have "list of product" screen, after which we have automatically **Subscribe** modal; in a loop; transaction never finishes.

**Comment by FuadEfendi** [comment]
Related:
https://community.revenuecat.com/sdks-51/purchases-purchasepackage-doesn-t-return-1956

- I am experiencing the same issue.

**Comment by john-paradym** [comment]
Extra info:
I did a Flutter hot reload and removed the Purchasely code, and got this error

`Product purchase for 'subs.par_9.99_30_3' failed with error: Error Domain=RevenueCat.ErrorCode Code=15 "The operation is already in progress for this product." UserInfo={readable_error_code=OPERATION_ALREADY_IN_PROGRESS_FOR_PRODUCT_ERROR, source_file=RevenueCat/PurchasesOrchestrator.swift:956, NSLocalizedDescription=The operation is already in progress for this product., source_function=addPurchaseCompletedCallback(productIdentifier:completion:)}`

From my point of view, the original purchase went through, and I was trying again - but clearly the RevenueCat code thinks otherwise, and hence why the `Purchases.purchasePackage()` call never returned
